// PORTS
export const GET_PORTS_START = "GET_PORTS_START"
export const GET_PORTS_SUCCESS = "GET_PORTS_SUCCESS"
export const GET_PORTS_ERROR = "GET_PORTS_ERROR"

// MESSAGE
export const SEND_MESSAGE_START = "SEND_MESSAGE_START"
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_ERROR = "SEND_MESSAGE_ERROR"